export const json_data = [
  {
    "id": 1,
    "restaurant_name": "Rose Garden",
    "address": "91 Heffernan Pass",
    "city": "Maardu",
    "phone_number": "278-416-4280",
    "cuisine_type": "American",
    "average_rating": 3.7,
    "opening_hours": "10:00 AM - 11:00 PM",
    "reservation_required": false,
    "images": [
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80"
    ],
    "menu": [
      {
        "id": 101,
        "dish_name": "Classic Burger",
        "image": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
        "description": "Juicy beef burger with lettuce, tomato and cheese.",
        "price": 12.99,
        "calories": 620,
        "ingredients": "Beef, cheese, lettuce, tomato, bun",
        "category": "Burger",
        "spicy_level": "Mild",
        "vegetarian": false,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 102,
        "dish_name": "Chicken Burger",
        "image": "https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=800&q=80",
        "description": "Crispy chicken burger with fresh vegetables.",
        "price": 11.99,
        "calories": 580,
        "ingredients": "Chicken, lettuce, tomato, bun",
        "category": "Burger",
        "spicy_level": "Medium",
        "vegetarian": false,
        "gluten_free": false,
        "chef_special": false
      },
      {
        "id": 103,
        "dish_name": "Cheese Burger",
        "image": "https://images.unsplash.com/photo-1550317138-10000687a72b?auto=format&fit=crop&w=800&q=80",
        "description": "Grilled beef burger topped with melted cheddar.",
        "price": 13.49,
        "calories": 680,
        "ingredients": "Beef, cheddar, onion, tomato, bun",
        "category": "Burger",
        "spicy_level": "Mild",
        "vegetarian": false,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 104,
        "dish_name": "French Fries",
        "image": "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80",
        "description": "Crispy golden fries seasoned with salt.",
        "price": 5.49,
        "calories": 320,
        "ingredients": "Potatoes, salt, oil",
        "category": "Appetizer",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": false
      },
      {
        "id": 105,
        "dish_name": "Onion Rings",
        "image": "https://images.unsplash.com/photo-1639024471283-03518883512d?auto=format&fit=crop&w=800&q=80",
        "description": "Crispy battered onion rings.",
        "price": 6.49,
        "calories": 350,
        "ingredients": "Onion, flour, oil",
        "category": "Appetizer",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      },
      {
        "id": 106,
        "dish_name": "Chocolate Cake",
        "image": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
        "description": "Rich chocolate cake with creamy frosting.",
        "price": 7.99,
        "calories": 450,
        "ingredients": "Chocolate, flour, sugar, cream",
        "category": "Dessert",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 107,
        "dish_name": "Cheesecake",
        "image": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80",
        "description": "Creamy cheesecake with a biscuit base.",
        "price": 8.49,
        "calories": 420,
        "ingredients": "Cream cheese, sugar, biscuit",
        "category": "Dessert",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      }
    ]
  },

  {
    "id": 2,
    "restaurant_name": "Spice Hub",
    "address": "42 Market Street",
    "city": "Ludhiana",
    "phone_number": "987-456-1230",
    "cuisine_type": "Indian",
    "average_rating": 4.5,
    "opening_hours": "11:00 AM - 11:30 PM",
    "reservation_required": true,
    "images": [
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=80"
    ],
    "menu": [
      {
        "id": 201,
        "dish_name": "Paneer Tikka",
        "image": "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80",
        "description": "Grilled paneer with Indian spices.",
        "price": 9.99,
        "calories": 380,
        "ingredients": "Paneer, yogurt, spices",
        "category": "Appetizer",
        "spicy_level": "Medium",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": true
      },
      {
        "id": 202,
        "dish_name": "Samosa",
        "image": "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
        "description": "Crispy pastry filled with spiced potatoes.",
        "price": 5.99,
        "calories": 280,
        "ingredients": "Potatoes, peas, flour, spices",
        "category": "Appetizer",
        "spicy_level": "Medium",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      },
      {
        "id": 203,
        "dish_name": "Butter Chicken",
        "image": "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80",
        "description": "Creamy tomato-based chicken curry.",
        "price": 14.99,
        "calories": 580,
        "ingredients": "Chicken, tomato, butter, cream",
        "category": "Main Course",
        "spicy_level": "Medium",
        "vegetarian": false,
        "gluten_free": true,
        "chef_special": true
      },
      {
        "id": 204,
        "dish_name": "Paneer Butter Masala",
        "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80",
        "description": "Paneer cooked in a rich buttery tomato gravy.",
        "price": 12.99,
        "calories": 520,
        "ingredients": "Paneer, tomato, butter, cream, spices",
        "category": "Main Course",
        "spicy_level": "Medium",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": true
      },
      {
        "id": 205,
        "dish_name": "Dal Makhani",
        "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80",
        "description": "Slow-cooked black lentils with butter and cream.",
        "price": 10.99,
        "calories": 410,
        "ingredients": "Black lentils, butter, cream, spices",
        "category": "Main Course",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": false
      },
      {
        "id": 206,
        "dish_name": "Gulab Jamun",
        "image": "https://images.unsplash.com/photo-1666190094766-5e0a1c1b1b44?auto=format&fit=crop&w=800&q=80",
        "description": "Soft milk dumplings soaked in sweet syrup.",
        "price": 5.99,
        "calories": 290,
        "ingredients": "Milk solids, sugar, cardamom",
        "category": "Dessert",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      },
      {
        "id": 207,
        "dish_name": "Rasmalai",
        "image": "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80",
        "description": "Soft cheese dumplings served in sweet saffron milk.",
        "price": 6.99,
        "calories": 310,
        "ingredients": "Milk, paneer, sugar, saffron",
        "category": "Dessert",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": true
      }
    ]
  },

  {
    "id": 3,
    "restaurant_name": "Bella Italia",
    "address": "18 Lake Avenue",
    "city": "Tallinn",
    "phone_number": "555-321-7890",
    "cuisine_type": "Italian",
    "average_rating": 4.2,
    "opening_hours": "12:00 PM - 10:30 PM",
    "reservation_required": false,
    "images": [
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80"
    ],
    "menu": [
      {
        "id": 301,
        "dish_name": "Margherita Pizza",
        "image": "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80",
        "description": "Classic pizza with tomato, mozzarella and basil.",
        "price": 11.99,
        "calories": 650,
        "ingredients": "Tomato, mozzarella, basil, flour",
        "category": "Pizza",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 302,
        "dish_name": "Veggie Pizza",
        "image": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80",
        "description": "Pizza topped with fresh seasonal vegetables.",
        "price": 13.49,
        "calories": 610,
        "ingredients": "Tomato, mozzarella, peppers, olives",
        "category": "Pizza",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      },
      {
        "id": 303,
        "dish_name": "Creamy Pasta",
        "image": "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=800&q=80",
        "description": "Pasta tossed in creamy parmesan sauce.",
        "price": 13.49,
        "calories": 590,
        "ingredients": "Pasta, cream, parmesan, garlic",
        "category": "Pasta",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      },
      {
        "id": 304,
        "dish_name": "Arrabbiata Pasta",
        "image": "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80",
        "description": "Pasta served with spicy tomato sauce.",
        "price": 12.49,
        "calories": 540,
        "ingredients": "Pasta, tomato, garlic, chili",
        "category": "Pasta",
        "spicy_level": "Hot",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 305,
        "dish_name": "Tiramisu",
        "image": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=800&q=80",
        "description": "Italian coffee-flavored layered dessert.",
        "price": 7.49,
        "calories": 410,
        "ingredients": "Mascarpone, coffee, cocoa, biscuits",
        "category": "Dessert",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 306,
        "dish_name": "Panna Cotta",
        "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80",
        "description": "Silky Italian cream dessert with berries.",
        "price": 7.99,
        "calories": 360,
        "ingredients": "Cream, sugar, vanilla, berries",
        "category": "Dessert",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": false
      }
    ]
  },

  {
    "id": 4,
    "restaurant_name": "Dragon Bowl",
    "address": "77 Central Road",
    "city": "Tartu",
    "phone_number": "555-654-1234",
    "cuisine_type": "Chinese",
    "average_rating": 4.1,
    "opening_hours": "11:30 AM - 10:00 PM",
    "reservation_required": false,
    "images": [
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80"
    ],
    "menu": [
      {
        "id": 401,
        "dish_name": "Veg Hakka Noodles",
        "image": "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=800&q=80",
        "description": "Stir-fried noodles with fresh vegetables.",
        "price": 8.99,
        "calories": 430,
        "ingredients": "Noodles, cabbage, carrots, peppers",
        "category": "Noodles",
        "spicy_level": "Medium",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      },
      {
        "id": 402,
        "dish_name": "Chicken Chow Mein",
        "image": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80",
        "description": "Stir-fried noodles with chicken and vegetables.",
        "price": 11.99,
        "calories": 520,
        "ingredients": "Noodles, chicken, cabbage, carrots",
        "category": "Noodles",
        "spicy_level": "Medium",
        "vegetarian": false,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 403,
        "dish_name": "Spring Rolls",
        "image": "https://images.unsplash.com/photo-1548507200-bc5e0a3c7f1f?auto=format&fit=crop&w=800&q=80",
        "description": "Crispy rolls filled with vegetables.",
        "price": 6.99,
        "calories": 290,
        "ingredients": "Cabbage, carrots, flour, oil",
        "category": "Appetizer",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 404,
        "dish_name": "Dumplings",
        "image": "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=800&q=80",
        "description": "Steamed dumplings filled with vegetables.",
        "price": 7.99,
        "calories": 310,
        "ingredients": "Flour, cabbage, carrots, spices",
        "category": "Appetizer",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      }
    ]
  },

  {
    "id": 5,
    "restaurant_name": "Green Leaf",
    "address": "12 Garden Lane",
    "city": "Pärnu",
    "phone_number": "555-111-2233",
    "cuisine_type": "Vegetarian",
    "average_rating": 4.6,
    "opening_hours": "9:00 AM - 9:00 PM",
    "reservation_required": false,
    "images": [
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1200&q=80"
    ],
    "menu": [
      {
        "id": 501,
        "dish_name": "Garden Salad",
        "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
        "description": "Fresh seasonal vegetables with house dressing.",
        "price": 8.49,
        "calories": 220,
        "ingredients": "Lettuce, tomato, cucumber, olives",
        "category": "Salad",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": true
      },
      {
        "id": 502,
        "dish_name": "Greek Salad",
        "image": "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
        "description": "Fresh vegetables with feta and olives.",
        "price": 9.49,
        "calories": 260,
        "ingredients": "Tomato, cucumber, feta, olives",
        "category": "Salad",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": false
      },
      {
        "id": 503,
        "dish_name": "Avocado Toast",
        "image": "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?auto=format&fit=crop&w=800&q=80",
        "description": "Toasted bread topped with creamy avocado.",
        "price": 7.99,
        "calories": 340,
        "ingredients": "Avocado, bread, lemon, herbs",
        "category": "Breakfast",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      },
      {
        "id": 504,
        "dish_name": "Veggie Sandwich",
        "image": "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
        "description": "Fresh vegetables layered inside toasted bread.",
        "price": 8.99,
        "calories": 390,
        "ingredients": "Bread, lettuce, tomato, cucumber, cheese",
        "category": "Breakfast",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      }
    ]
  },

  {
    "id": 6,
    "restaurant_name": "Ocean Catch",
    "address": "34 Harbor Road",
    "city": "Haapsalu",
    "phone_number": "555-222-3344",
    "cuisine_type": "Seafood",
    "average_rating": 4.3,
    "opening_hours": "12:00 PM - 11:00 PM",
    "reservation_required": true,
    "images": [
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80"
    ],
    "menu": [
      {
        "id": 601,
        "dish_name": "Grilled Salmon",
        "image": "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=80",
        "description": "Fresh salmon grilled with herbs and lemon.",
        "price": 17.99,
        "calories": 480,
        "ingredients": "Salmon, lemon, herbs, olive oil",
        "category": "Main Course",
        "spicy_level": "Mild",
        "vegetarian": false,
        "gluten_free": true,
        "chef_special": true
      },
      {
        "id": 602,
        "dish_name": "Grilled Shrimp",
        "image": "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?auto=format&fit=crop&w=800&q=80",
        "description": "Seasoned shrimp grilled with garlic and herbs.",
        "price": 15.99,
        "calories": 390,
        "ingredients": "Shrimp, garlic, herbs, butter",
        "category": "Main Course",
        "spicy_level": "Mild",
        "vegetarian": false,
        "gluten_free": true,
        "chef_special": true
      },
      {
        "id": 603,
        "dish_name": "Shrimp Cocktail",
        "image": "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?auto=format&fit=crop&w=800&q=80",
        "description": "Chilled shrimp served with cocktail sauce.",
        "price": 12.99,
        "calories": 250,
        "ingredients": "Shrimp, tomato, lemon",
        "category": "Appetizer",
        "spicy_level": "Mild",
        "vegetarian": false,
        "gluten_free": true,
        "chef_special": false
      },
      {
        "id": 604,
        "dish_name": "Calamari",
        "image": "https://images.unsplash.com/photo-1604909052743-94e838986d24?auto=format&fit=crop&w=800&q=80",
        "description": "Crispy fried calamari with lemon.",
        "price": 13.49,
        "calories": 420,
        "ingredients": "Squid, flour, lemon, oil",
        "category": "Appetizer",
        "spicy_level": "Mild",
        "vegetarian": false,
        "gluten_free": false,
        "chef_special": false
      }
    ]
  },

  {
    "id": 7,
    "restaurant_name": "Burger Point",
    "address": "55 Main Street",
    "city": "Narva",
    "phone_number": "555-333-4455",
    "cuisine_type": "Fast Food",
    "average_rating": 3.9,
    "opening_hours": "10:00 AM - 12:00 AM",
    "reservation_required": false,
    "images": [
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1550317138-10000687a72b?auto=format&fit=crop&w=1200&q=80"
    ],
    "menu": [
      {
        "id": 701,
        "dish_name": "Double Cheeseburger",
        "image": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
        "description": "Two beef patties with melted cheese.",
        "price": 10.99,
        "calories": 720,
        "ingredients": "Beef, cheese, lettuce, tomato, bun",
        "category": "Burger",
        "spicy_level": "Mild",
        "vegetarian": false,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 702,
        "dish_name": "Chicken Burger",
        "image": "https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=800&q=80",
        "description": "Crispy chicken fillet with fresh vegetables.",
        "price": 9.99,
        "calories": 590,
        "ingredients": "Chicken, lettuce, tomato, bun",
        "category": "Burger",
        "spicy_level": "Medium",
        "vegetarian": false,
        "gluten_free": false,
        "chef_special": false
      },
      {
        "id": 703,
        "dish_name": "Bacon Burger",
        "image": "https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=800&q=80",
        "description": "Beef burger topped with crispy bacon.",
        "price": 13.99,
        "calories": 760,
        "ingredients": "Beef, bacon, cheese, lettuce, bun",
        "category": "Burger",
        "spicy_level": "Mild",
        "vegetarian": false,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 704,
        "dish_name": "Loaded Fries",
        "image": "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80",
        "description": "Fries topped with cheese and sauces.",
        "price": 7.99,
        "calories": 510,
        "ingredients": "Potatoes, cheese, sauce",
        "category": "Appetizer",
        "spicy_level": "Medium",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": true
      }
    ]
  },

  {
    "id": 8,
    "restaurant_name": "Sushi House",
    "address": "21 River Street",
    "city": "Viljandi",
    "phone_number": "555-444-5566",
    "cuisine_type": "Japanese",
    "average_rating": 4.7,
    "opening_hours": "12:00 PM - 10:00 PM",
    "reservation_required": true,
    "images": [
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?auto=format&fit=crop&w=1200&q=80"
    ],
    "menu": [
      {
        "id": 801,
        "dish_name": "Salmon Sushi",
        "image": "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80",
        "description": "Fresh salmon served over seasoned sushi rice.",
        "price": 13.99,
        "calories": 360,
        "ingredients": "Salmon, rice, seaweed",
        "category": "Sushi",
        "spicy_level": "Mild",
        "vegetarian": false,
        "gluten_free": true,
        "chef_special": true
      },
      {
        "id": 802,
        "dish_name": "Vegetable Roll",
        "image": "https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=800&q=80",
        "description": "Fresh vegetables wrapped in sushi rice.",
        "price": 9.99,
        "calories": 280,
        "ingredients": "Cucumber, avocado, carrot, rice",
        "category": "Sushi",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": false
      },
      {
        "id": 803,
        "dish_name": "Tuna Roll",
        "image": "https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=800&q=80",
        "description": "Fresh tuna rolled with sushi rice and seaweed.",
        "price": 12.99,
        "calories": 330,
        "ingredients": "Tuna, rice, seaweed",
        "category": "Sushi",
        "spicy_level": "Mild",
        "vegetarian": false,
        "gluten_free": true,
        "chef_special": true
      },
      {
        "id": 804,
        "dish_name": "Edamame",
        "image": "https://images.unsplash.com/photo-1564894809611-1742fc40ed80?auto=format&fit=crop&w=800&q=80",
        "description": "Steamed soybeans lightly seasoned with salt.",
        "price": 5.99,
        "calories": 190,
        "ingredients": "Soybeans, salt",
        "category": "Appetizer",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": false
      }
    ]
  },

  {
    "id": 9,
    "restaurant_name": "Taco Fiesta",
    "address": "88 Sunset Boulevard",
    "city": "Rakvere",
    "phone_number": "555-555-6677",
    "cuisine_type": "Mexican",
    "average_rating": 4.0,
    "opening_hours": "11:00 AM - 11:00 PM",
    "reservation_required": false,
    "images": [
      "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1200&q=80"
    ],
    "menu": [
      {
        "id": 901,
        "dish_name": "Chicken Tacos",
        "image": "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=800&q=80",
        "description": "Soft tacos filled with seasoned chicken.",
        "price": 10.99,
        "calories": 430,
        "ingredients": "Chicken, tortilla, salsa, lettuce",
        "category": "Tacos",
        "spicy_level": "Medium",
        "vegetarian": false,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 902,
        "dish_name": "Beef Tacos",
        "image": "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80",
        "description": "Seasoned beef tacos with salsa and vegetables.",
        "price": 11.99,
        "calories": 460,
        "ingredients": "Beef, tortilla, salsa, onion",
        "category": "Tacos",
        "spicy_level": "Medium",
        "vegetarian": false,
        "gluten_free": false,
        "chef_special": false
      },
      {
        "id": 903,
        "dish_name": "Vegetable Tacos",
        "image": "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=800&q=80",
        "description": "Fresh vegetables wrapped in soft tortillas.",
        "price": 9.49,
        "calories": 350,
        "ingredients": "Peppers, corn, beans, tortilla",
        "category": "Tacos",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      },
      {
        "id": 904,
        "dish_name": "Guacamole",
        "image": "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=800&q=80",
        "description": "Fresh avocado dip with lime and herbs.",
        "price": 6.49,
        "calories": 220,
        "ingredients": "Avocado, lime, onion, cilantro",
        "category": "Appetizer",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": false
      }
    ]
  },

  {
    "id": 10,
    "restaurant_name": "Steak House",
    "address": "15 King Road",
    "city": "Pärnu",
    "phone_number": "555-666-7788",
    "cuisine_type": "Steakhouse",
    "average_rating": 4.4,
    "opening_hours": "5:00 PM - 11:30 PM",
    "reservation_required": true,
    "images": [
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80"
    ],
    "menu": [
      {
        "id": 1001,
        "dish_name": "Grilled Ribeye",
        "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80",
        "description": "Tender ribeye steak grilled to your preference.",
        "price": 24.99,
        "calories": 720,
        "ingredients": "Beef, salt, pepper, butter",
        "category": "Steak",
        "spicy_level": "Mild",
        "vegetarian": false,
        "gluten_free": true,
        "chef_special": true
      },
      {
        "id": 1002,
        "dish_name": "New York Strip",
        "image": "https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=800&q=80",
        "description": "Juicy strip steak seasoned with herbs.",
        "price": 22.99,
        "calories": 680,
        "ingredients": "Beef, herbs, butter",
        "category": "Steak",
        "spicy_level": "Mild",
        "vegetarian": false,
        "gluten_free": true,
        "chef_special": true
      },
      {
        "id": 1003,
        "dish_name": "Garlic Bread",
        "image": "https://images.unsplash.com/photo-1573140401552-3fab0b24306f?auto=format&fit=crop&w=800&q=80",
        "description": "Toasted bread with garlic butter.",
        "price": 5.99,
        "calories": 280,
        "ingredients": "Bread, garlic, butter",
        "category": "Appetizer",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      },
      {
        "id": 1004,
        "dish_name": "Mashed Potatoes",
        "image": "https://images.unsplash.com/photo-1600175074390-6d0c1a2d1c1b?auto=format&fit=crop&w=800&q=80",
        "description": "Creamy mashed potatoes with butter.",
        "price": 6.99,
        "calories": 310,
        "ingredients": "Potatoes, butter, milk",
        "category": "Side Dish",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": false
      }
    ]
  },

  {
    "id": 11,
    "restaurant_name": "Morning Brew",
    "address": "27 Coffee Lane",
    "city": "Tallinn",
    "phone_number": "555-777-8899",
    "cuisine_type": "Cafe",
    "average_rating": 4.3,
    "opening_hours": "7:00 AM - 8:00 PM",
    "reservation_required": false,
    "images": [
      "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1200&q=80"
    ],
    "menu": [
      {
        "id": 1101,
        "dish_name": "Cappuccino",
        "image": "https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=800&q=80",
        "description": "Espresso with steamed milk and foam.",
        "price": 4.99,
        "calories": 120,
        "ingredients": "Espresso, milk",
        "category": "Beverage",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": false
      },
      {
        "id": 1102,
        "dish_name": "Latte",
        "image": "https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=800&q=80",
        "description": "Smooth espresso with steamed milk.",
        "price": 4.49,
        "calories": 140,
        "ingredients": "Espresso, milk",
        "category": "Beverage",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": false
      },
      {
        "id": 1103,
        "dish_name": "Pancakes",
        "image": "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=800&q=80",
        "description": "Fluffy pancakes served with fresh berries.",
        "price": 8.99,
        "calories": 440,
        "ingredients": "Flour, eggs, milk, berries",
        "category": "Breakfast",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 1104,
        "dish_name": "French Toast",
        "image": "https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=800&q=80",
        "description": "Golden French toast served with berries.",
        "price": 8.49,
        "calories": 410,
        "ingredients": "Bread, eggs, milk, berries",
        "category": "Breakfast",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      }
    ]
  },

  {
    "id": 12,
    "restaurant_name": "Thai Orchid",
    "address": "63 Garden Street",
    "city": "Tartu",
    "phone_number": "555-888-9900",
    "cuisine_type": "Thai",
    "average_rating": 4.5,
    "opening_hours": "11:30 AM - 10:30 PM",
    "reservation_required": false,
    "images": [
      "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80"
    ],
    "menu": [
      {
        "id": 1201,
        "dish_name": "Pad Thai",
        "image": "https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=800&q=80",
        "description": "Thai rice noodles stir-fried with vegetables.",
        "price": 11.99,
        "calories": 510,
        "ingredients": "Rice noodles, vegetables, peanuts, tofu",
        "category": "Noodles",
        "spicy_level": "Medium",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": true
      },
      {
        "id": 1202,
        "dish_name": "Thai Green Curry",
        "image": "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=800&q=80",
        "description": "Creamy coconut curry with Thai herbs.",
        "price": 13.99,
        "calories": 560,
        "ingredients": "Coconut milk, vegetables, basil, curry paste",
        "category": "Curry",
        "spicy_level": "Hot",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": true
      },
      {
        "id": 1203,
        "dish_name": "Red Curry",
        "image": "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=800&q=80",
        "description": "Spicy red curry with coconut milk.",
        "price": 13.49,
        "calories": 570,
        "ingredients": "Coconut milk, vegetables, red curry paste",
        "category": "Curry",
        "spicy_level": "Hot",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": false
      },
      {
        "id": 1204,
        "dish_name": "Thai Spring Rolls",
        "image": "https://images.unsplash.com/photo-1548507200-bc5e0a3c7f1f?auto=format&fit=crop&w=800&q=80",
        "description": "Crispy vegetable rolls served with sweet chili sauce.",
        "price": 7.49,
        "calories": 300,
        "ingredients": "Vegetables, flour, oil, chili sauce",
        "category": "Appetizer",
        "spicy_level": "Medium",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      }
    ]
  },

  {
    "id": 13,
    "restaurant_name": "Sweet Corner",
    "address": "39 Palace Road",
    "city": "Viljandi",
    "phone_number": "555-999-0011",
    "cuisine_type": "Bakery",
    "average_rating": 4.8,
    "opening_hours": "8:00 AM - 9:00 PM",
    "reservation_required": false,
    "images": [
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=1200&q=80"
    ],
    "menu": [
      {
        "id": 1301,
        "dish_name": "Croissant",
        "image": "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80",
        "description": "Buttery and flaky French-style croissant.",
        "price": 4.49,
        "calories": 270,
        "ingredients": "Flour, butter, milk, sugar",
        "category": "Bakery",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 1302,
        "dish_name": "Blueberry Muffin",
        "image": "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&w=800&q=80",
        "description": "Soft muffin filled with fresh blueberries.",
        "price": 4.99,
        "calories": 330,
        "ingredients": "Flour, blueberries, sugar, butter",
        "category": "Bakery",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      },
      {
        "id": 1303,
        "dish_name": "Strawberry Cake",
        "image": "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=800&q=80",
        "description": "Light sponge cake topped with strawberries.",
        "price": 8.49,
        "calories": 390,
        "ingredients": "Flour, eggs, cream, strawberries",
        "category": "Dessert",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 1304,
        "dish_name": "Chocolate Tart",
        "image": "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=800&q=80",
        "description": "Rich chocolate tart with a buttery crust.",
        "price": 7.99,
        "calories": 430,
        "ingredients": "Chocolate, flour, butter, sugar",
        "category": "Dessert",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": true
      }
    ]
  },

  {
    "id": 14,
    "restaurant_name": "Urban Bites",
    "address": "24 Downtown Avenue",
    "city": "Ludhiana",
    "phone_number": "555-123-4567",
    "cuisine_type": "Continental",
    "average_rating": 4.1,
    "opening_hours": "11:00 AM - 11:00 PM",
    "reservation_required": false,
    "images": [
      "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80"
    ],
    "menu": [
      {
        "id": 1401,
        "dish_name": "Grilled Chicken",
        "image": "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=800&q=80",
        "description": "Herb-marinated chicken grilled to perfection.",
        "price": 14.99,
        "calories": 480,
        "ingredients": "Chicken, herbs, olive oil",
        "category": "Main Course",
        "spicy_level": "Mild",
        "vegetarian": false,
        "gluten_free": true,
        "chef_special": true
      },
      {
        "id": 1402,
        "dish_name": "Grilled Vegetables",
        "image": "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
        "description": "Seasonal vegetables grilled with herbs.",
        "price": 9.49,
        "calories": 230,
        "ingredients": "Zucchini, peppers, broccoli, herbs",
        "category": "Main Course",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": false
      },
      {
        "id": 1403,
        "dish_name": "Garlic Bread",
        "image": "https://images.unsplash.com/photo-1573140401552-3fab0b24306f?auto=format&fit=crop&w=800&q=80",
        "description": "Toasted bread with garlic butter.",
        "price": 5.99,
        "calories": 280,
        "ingredients": "Bread, garlic, butter",
        "category": "Appetizer",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      },
      {
        "id": 1404,
        "dish_name": "Caesar Salad",
        "image": "https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&w=800&q=80",
        "description": "Crisp lettuce with parmesan and Caesar dressing.",
        "price": 8.99,
        "calories": 320,
        "ingredients": "Lettuce, parmesan, croutons, dressing",
        "category": "Salad",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      }
    ]
  },

  {
    "id": 15,
    "restaurant_name": "Pizza Palace",
    "address": "76 Station Road",
    "city": "Chandigarh",
    "phone_number": "555-456-7890",
    "cuisine_type": "Pizza",
    "average_rating": 4.4,
    "opening_hours": "11:00 AM - 12:00 AM",
    "reservation_required": false,
    "images": [
      "https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1200&q=80"
    ],
    "menu": [
      {
        "id": 1501,
        "dish_name": "Pepperoni Pizza",
        "image": "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=800&q=80",
        "description": "Classic pizza topped with pepperoni and mozzarella.",
        "price": 14.99,
        "calories": 720,
        "ingredients": "Pepperoni, mozzarella, tomato sauce, flour",
        "category": "Pizza",
        "spicy_level": "Medium",
        "vegetarian": false,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 1502,
        "dish_name": "Margherita Pizza",
        "image": "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80",
        "description": "Tomato, mozzarella and fresh basil.",
        "price": 11.99,
        "calories": 650,
        "ingredients": "Tomato, mozzarella, basil, flour",
        "category": "Pizza",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      },
      {
        "id": 1503,
        "dish_name": "BBQ Chicken Pizza",
        "image": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80",
        "description": "Pizza topped with BBQ chicken and onions.",
        "price": 15.49,
        "calories": 690,
        "ingredients": "Chicken, BBQ sauce, mozzarella, onion",
        "category": "Pizza",
        "spicy_level": "Medium",
        "vegetarian": false,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 1504,
        "dish_name": "Cheesy Garlic Bread",
        "image": "https://images.unsplash.com/photo-1573140401552-3fab0b24306f?auto=format&fit=crop&w=800&q=80",
        "description": "Garlic bread covered with melted cheese.",
        "price": 6.99,
        "calories": 360,
        "ingredients": "Bread, garlic, butter, cheese",
        "category": "Appetizer",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      }
    ]
  },

  {
    "id": 16,
    "restaurant_name": "Curry Leaf",
    "address": "19 Green Avenue",
    "city": "Amritsar",
    "phone_number": "555-987-6543",
    "cuisine_type": "Indian",
    "average_rating": 4.6,
    "opening_hours": "11:00 AM - 11:30 PM",
    "reservation_required": true,
    "images": [
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=80"
    ],
    "menu": [
      {
        "id": 1601,
        "dish_name": "Chole Bhature",
        "image": "https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=800&q=80",
        "description": "Spiced chickpeas served with fluffy fried bread.",
        "price": 9.99,
        "calories": 610,
        "ingredients": "Chickpeas, flour, spices, oil",
        "category": "Main Course",
        "spicy_level": "Medium",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": true
      },
      {
        "id": 1602,
        "dish_name": "Dal Tadka",
        "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80",
        "description": "Yellow lentils tempered with garlic and spices.",
        "price": 8.99,
        "calories": 360,
        "ingredients": "Lentils, garlic, cumin, spices",
        "category": "Main Course",
        "spicy_level": "Medium",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": false
      },
      {
        "id": 1603,
        "dish_name": "Tandoori Chicken",
        "image": "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=80",
        "description": "Chicken marinated in yogurt and roasted with spices.",
        "price": 15.99,
        "calories": 490,
        "ingredients": "Chicken, yogurt, spices, lemon",
        "category": "Tandoor",
        "spicy_level": "Hot",
        "vegetarian": false,
        "gluten_free": true,
        "chef_special": true
      },
      {
        "id": 1604,
        "dish_name": "Garlic Naan",
        "image": "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=800&q=80",
        "description": "Soft naan topped with garlic and coriander.",
        "price": 4.99,
        "calories": 290,
        "ingredients": "Flour, garlic, butter, coriander",
        "category": "Bread",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": false
      },
      {
        "id": 1605,
        "dish_name": "Kheer",
        "image": "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80",
        "description": "Creamy rice pudding flavored with cardamom.",
        "price": 5.99,
        "calories": 300,
        "ingredients": "Rice, milk, sugar, cardamom",
        "category": "Dessert",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": true,
        "chef_special": false
      },
      {
        "id": 1606,
        "dish_name": "Jalebi",
        "image": "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
        "description": "Crispy spiral-shaped sweets soaked in sugar syrup.",
        "price": 5.49,
        "calories": 330,
        "ingredients": "Flour, sugar, saffron, oil",
        "category": "Dessert",
        "spicy_level": "Mild",
        "vegetarian": true,
        "gluten_free": false,
        "chef_special": true
      }
    ]
  }
]